### ISSUE TITLE
ТГ

### ISSUE THREAD

**Issue by KrasProject2021** [huntmix/pentutor#2]
Здорово. У вас есть телеграм канал ?

**Comment by huntmix** [comment]
> Здорово. У вас есть телеграм канал ?

На данный момент нет. Разработка приложения _завершена_. Сайт не поддерживается. Если есть другие вопросы можно спросить **здесь** либо на почту **huntmix@protonmail.com**

**Comment by huntmix** [comment]
Ранее был канал pentestershome, но сейчас я не имею к нему никакого отношения

**Comment by KrasProject2021** [comment]
Ясно, если не секрет, почему разработка приложения остановлена ?

**Comment by huntmix** [comment]
> Ясно, если не секрет, почему разработка приложения остановлена ?

Многие начинали таскать контент в тг помойки

Да и вообще контента очень много а приложении для новичков
